name: concepts
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.9
  - pytorch
  - torchvision
  - scikit-learn
  - matplotlib
  - pillow
  - captum
  - opencv
  - scikit-image
  - numpy
  - scipy
  - jupyter